version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8.1.9-fpm
        container_name: app-slim
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8888:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
